Add support for query-based probabilistic facts
NeuroLang/NeuroLang pull request #548
Opened 2020-11-09 09:55 UTC by tgy

2020-11-09 09:59 UTC, tgy commented
This docstring describes my approach

    Translate a query-based probabilistic fact to two rules. A deterministic
    rule that takes care of inferring the set of tuples in the probabilistic
    table and a probabilistic rule that transforms the result from the
    deterministic resolution into a proper probabilistic table by re-attaching
    the deterministically-obtained probabilities.
    For example, the rule `P(x) : f(x) :- Q(x)` is translated into the rules
        _f1_(_f2_, x) :- Q(x), _f2_ = f(x)
        P(x) : _f2_ :- _f1_(_f2_, x)
    where `_f1_` and `_f2_` are fresh symbols. Note: we make sure not to
    expose the resulting `_f1_` relation to the user, as it is not part of
    its program.

@demianw I would like to know if you think this is the right approach

2020-11-10 14:11 UTC, demianw commented on neurolang/expressions.py
> +MATMUL = Constant(
I think that this represents non-consistent semantics. Either all operators are here or none. For now, let's go for none.

2020-11-10 14:13 UTC, demianw commented on neurolang/probabilistic/expressions.py
> +    def functor(self):
Maybe we could call it ProbabilisticDecorator? Which decorates anything with a probability? Or just keep it as a probabilistic predicate but make it a three-parameter expression (functor, args, probability)

2020-11-12 07:50 UTC, tgy commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> +    from ...logic import Conjunction, Implication
I put these imports here because, since we are in the probabilistic frontend tests, I should not have to import these IR classes. As the resolution of variable equalities of the form `x = f(g(x))` does not work, I have to use the trick below to convert `x = volume(y) / volume(z)` to `x = _f1_ / _f2_, _f1_ = volume(y), _f2_ = volume(z)`.

2020-11-12 08:52 UTC, demianw requested changes
Many comments. Ignoring everything related to probabilistic facts as that's in PR #549 I assume. There are still reformatting / renaming diffs in this PR. This still forces me to deal with non-essential information in the PR, please be more careful in the future @tgy . Keep the renaming / styling out of the PR until all logic has been reviewed and approved.

2020-11-12 08:52 UTC, demianw commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> +    class VolumeDivisionEqualityRewritter(PatternWalker):
this is specific to formula compositions. My question is why isn't this working directly. It should be well-translated and compiled by the RA translator. Where is the issue? This is a very specific fix which will not generalise and bring problems down the road.

2020-11-12 08:52 UTC, demianw commented on neurolang/probabilistic/cplogic/program.py
> +from ...expressions import MATMUL, Constant, FunctionApplication, Symbol
check my comment about me disagreeing with the way you handle the MATMUL constant

2020-11-12 08:52 UTC, demianw commented on neurolang/probabilistic/cplogic/program.py
> +            FunctionApplication(MATMUL(Symbol, ...), ...),
This seems to be sugar which is more appropriate to the frontend. Even if it works at the IR level it should be a model in the frontend. Check my PR https://github.com/NeuroLang/NeuroLang/pull/535 as an example of the architectural choice of sugar.

2020-11-12 08:52 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +        return impl
if you have changed impl then you should re-walk it, if not this is not a composable mixin

2020-11-12 08:58 UTC, tgy commented on neurolang/probabilistic/cplogic/program.py
> +            FunctionApplication(MATMUL(Symbol, ...), ...),
Then maybe `TranslateProbabilisticQueryMixin`, which handles the `//` syntax for MARG queries should also be in the frontend module? You put it in the `neurolang/probabilistic/cplogic/program.py` module as well.

2020-11-12 09:04 UTC, tgy commented on neurolang/expressions.py
> +MATMUL = Constant(
fixed

2020-11-12 09:09 UTC, demianw commented on neurolang/probabilistic/cplogic/program.py
> +            FunctionApplication(MATMUL(Symbol, ...), ...),
You are right!!! @tgy let's merge it like this and then refactor both of them out, we should put "sugars" in the frontend. It was my bad before.

2020-11-12 09:23 UTC, tgy commented on neurolang/probabilistic/expressions.py
> +    def functor(self):
agreed to leave that for later, opened https://github.com/NeuroLang/NeuroLang/issues/559 for posterity

2020-11-16 09:58 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +        return impl
This has now been fixed. Note that I had to add a pattern for a Union containing a query-based probabilistic fact because the current pattern matching system makes it not convenient to return a Union of multiple formulas when walking a single formula. This leads to rules being walked multiple times (as the Union is re-walked when modified, by the `ExpressionWalker` mixin).

2020-11-16 09:58 UTC, tgy commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> +    from ...logic import Conjunction, Implication
Has been removed now that this is working

2020-11-18 14:58 UTC, tgy commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> +    class VolumeDivisionEqualityRewritter(PatternWalker):
has been removed

2020-11-18 14:58 UTC, tgy commented on neurolang/probabilistic/cplogic/program.py
> +from ...expressions import MATMUL, Constant, FunctionApplication, Symbol
has been solved

2020-11-18 14:59 UTC, tgy commented
@demianw any idea why the test suite is not being ran on this PR?

2020-11-18 15:23 UTC, demianw commented
Nope, maybe you'll find insight here? https://app.circleci.com/pipelines/github/NeuroLang

2020-11-18 15:33 UTC, demianw requested changes
Good job! Very minor changes

2020-11-18 15:33 UTC, demianw commented on neurolang/probabilistic/cplogic/program.py
> +class TranslateQueryBasedProbabilisticFactMixin(PatternWalker):
I think that now you can move this to https://github.com/NeuroLang/NeuroLang/blob/master/neurolang/frontend/datalog/intermediate_sugar.py

2020-11-18 15:33 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +    def union_with_query_based_pfact(self, union):
Do you need this if you have the Implication case?

2020-11-19 14:51 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +    def union_with_query_based_pfact(self, union):
I tried not to have this pattern. It does not work because the implication pattern returns TWO expressions. As we've seen before, our pattern matching system is not well suited to handle a case where we walk a Union of rules, one of which becomes several rules. We first walk the Union returned when walking the rule, and then the wrapper Union is modified and we re-walk the rules again. This results in the rules being walked multiple times. Attempting to do this, in this case, breaks the Forbidden Disjunction assumption of CP Logic program. If you have a better solution, I'm all ears

2020-11-19 14:51 UTC, tgy commented on neurolang/probabilistic/cplogic/program.py
> +class TranslateQueryBasedProbabilisticFactMixin(PatternWalker):
done

2020-11-19 15:00 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +    def union_with_query_based_pfact(self, union):
OK It was a question. Good job

2020-11-19 15:03 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +    def union_with_query_based_pfact(self, union):
sure! i think we should come up with a strategy to handle these cases where one rule becomes multiple rules. i think it's the 3rd time that i have to work around this limitation with a pattern such as this one. i opened an issue for it a while ago, so no need to open another

2020-11-19 15:06 UTC, demianw approved these changes
It's great. Can you just add a test case where the stratification fails such that we know that we throw the good error? Basically there is a probabilistic predicate on a query-based probabilistic fact?

2020-11-19 15:08 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +    def union_with_query_based_pfact(self, union):
You can check how @Jbat1Jumper solved it on `Fol2DatalogMixin` I think he solved well there.

2020-11-20 12:42 UTC, demianw commented
@tgy did you see my comment?

2020-11-20 13:04 UTC, tgy commented
good catch, this was not correctly handled, fixed

2020-11-20 14:46 UTC, merged