Spatial prior through query-based probabilistic facts
NeuroLang/NeuroLang pull request #585
Opened 2020-12-03 16:54 UTC by tgy

2021-01-18 16:33 UTC, tgy commented on neurolang/datalog/expression_processing.py
> +        FunctionApplication(Symbol, ...),
more restrictive pattern to be able to catch builtin function applications in other pattern

2021-01-18 16:33 UTC, tgy commented on neurolang/datalog/expression_processing.py
> +    return (
used to detect equalities where the lhs is not the symbol (e.g. `EUCLIDEAN(...) = d`)

2021-01-18 16:33 UTC, tgy commented on neurolang/datalog/wrapped_collections.py
> +            return False
we added this during our pair programming session @demianw

2021-01-18 16:33 UTC, tgy commented on neurolang/utils/relational_algebra_set/pandas.py
> +        other._drop_duplicates_if_needed()
we added this to optimise the code

2021-01-18 17:25 UTC, demianw requested changes
Very good job. The example reads beautifully. As this PR spills across different changes and modules there are changes in each of them.

2021-01-18 17:25 UTC, demianw commented on neurolang/frontend/datalog/sugar/__init__.py
> +        new_expression = TranslateSSugarToSelectByColumn._convert_attr_s__to_SelectByColumn.walk(
Less clear code due to very opinionated formatting, please roll-back

2021-01-18 17:25 UTC, demianw commented on neurolang/frontend/datalog/sugar/spatial.py
> +        - a formula of the form `d < MAX_DIST`, where MAX_DIST is a constant
Could you capture cases where "d == EUCLIDEAN" is present but there is no bound `d < MAX_DIST` and throw an error? I think it's a safer way to implement the sugar case without a user making mistakes until we figure out how to implement more general patterns.

2021-01-18 17:25 UTC, demianw commented on neurolang/frontend/datalog/sugar/tests/test_spatial.py
> +                EQ(d, EUCLIDEAN(i1, j1, k1, i2, j2, k2)),
I think we need to add tests for `EQ(EUCLIDEAN(..), d)` and for `GT(max_dist, d)` both which should work or throw an error. And tests for throwing an error on all cases which are not yet captured by the sugar

2021-01-18 17:25 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +        and not hasattr(implication, "__already_walked__"),
This is a bit dirty, are we sure there is no other way to guarantee that we are no walking it twice? This is type of patterns that solve something now but generate inconsistent coding systems later and hence bugs which are impossible to catch.

2021-01-18 17:25 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__already_walked__")
This is a bit dirty, are we sure there is no other way to guarantee that we are no walking it twice? This is type of patterns that solve something now but generate inconsistent coding systems later and hence bugs which are impossible to catch.

2021-01-18 17:25 UTC, demianw commented on neurolang/utils/relational_algebra_set/pandas.py
> +        other._drop_duplicates_if_needed()
This should first be verified that it doesn't make the rest of the cases slower. Can you please use [asv](https://asv.readthedocs.io/en/stable/) to run the chase benchmarks and compare this and the master to see that it doesn't make us suffer on other cases?

2021-01-18 17:25 UTC, demianw commented on examples/plot_cbma_spatial_prior.py
> +###############################################################################
MINOR: add a `# %%` above each title if you can it will be great to translate them into notebooks making them compatible with [jupytext percent style](https://jupytext.readthedocs.io/en/latest/formats.html#the-percent-format) .

2021-01-18 17:47 UTC, tgy commented on examples/plot_cbma_spatial_prior.py
> +###############################################################################
good idea, i'll do that

2021-01-18 22:56 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__already_walked__")
I fully agree with you. This is dirty. I would love a better solution than this one. I could not find any other solution to prevent infinite recursion. This comes back to handling patterns that match a single rule but that can then generate multiple rules. You mentioned that @Jbat1Jumper implemented something that handles that well in the logic module? I could not find anything that does that. Do you remember more precisely where it was? Alternatively, do you have a cleaner solution that this one? I could not come up with something better yet.

2021-01-18 22:56 UTC, tgy commented on neurolang/frontend/datalog/sugar/tests/test_spatial.py
> +                EQ(d, EUCLIDEAN(i1, j1, k1, i2, j2, k2)),
i will add those

2021-01-19 09:47 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__already_walked__")
I improved the "tag"'s name a little bit, and also added a `TODO` comment

2021-01-19 09:47 UTC, tgy commented on neurolang/frontend/datalog/sugar/tests/test_spatial.py
> +                EQ(d, EUCLIDEAN(i1, j1, k1, i2, j2, k2)),
done

2021-01-19 09:55 UTC, tgy commented on neurolang/frontend/datalog/sugar/spatial.py
> +        - a formula of the form `d < MAX_DIST`, where MAX_DIST is a constant
done

2021-01-19 09:55 UTC, tgy commented on neurolang/frontend/datalog/sugar/__init__.py
> +        new_expression = TranslateSSugarToSelectByColumn._convert_attr_s__to_SelectByColumn.walk(
done

2021-01-19 10:28 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__already_walked__")
OK, great I will see if I can figure out a better way to do this (I'll have to understand the essence of the algorithm first feel free to help, but low priority on your list)

2021-01-19 12:25 UTC, demianw commented on examples/plot_cbma_spatial_prior.py
> +# %% [markdown]
Careful, I was suggesting just adding the "# %%" on top for a reason (https://sphinx-gallery.github.io/stable/tutorials/plot_parse.html ) to keep the notebook bi-compatible between jupytext and sphinx-gallery

2021-01-21 12:42 UTC, tgy commented
@demianw I've re-ran the benchmark for the current branch. the drop duplicate function is now called only for natural join and set substraction

the output of the benchmark now says `BENCHMARKS NOT SIGNIFICANTLY CHANGED.` for `asv continuous -v $(git rev-parse origin/master) $(git rev-parse HEAD) --environment=conda:3.7` on the `drago` machine.

2021-01-21 12:45 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__already_walked__")
@demianw did you see the docstring just above? i documented the algorithm in the class. i think this was my best attempt at explaining what the algorithm is doing. let me know if i can help explaining this further

2021-01-21 14:42 UTC, demianw requested changes
Just one comment @tgy let me know what you think about it.

2021-01-21 14:42 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__QueryBasedProbFactToDetRule__")
Maybe we could check here just that it's a `is_query_based_probfact(formula)` and the body requires the rewriting step? I'm guessing that checking that the body is a single predicate and `_f2_` is a variable on such predicate would suffice no? Then the only probfact required rewriting are the ones that are not like that. This will eliminate some trivial rewritings *and* the need for the new attribute. What do you think @tgy ?

2021-01-26 07:24 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__QueryBasedProbFactToDetRule__")
@tgy we will need to solve this before merging. Mainly because it's leaving/based on underspecified attributes in objects and that breeds for poor maintainability

2021-01-26 16:56 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +            and not hasattr(formula, "__QueryBasedProbFactToDetRule__")
see last commit

2021-01-26 17:29 UTC, merged