Handle tuple unicity and aggregation in query-based probabilistic facts
NeuroLang/NeuroLang pull request #611
Opened 2021-02-26 09:18 UTC by tgy

2021-02-26 09:19 UTC, tgy commented on neurolang/frontend/probabilistic_frontend.py
> +        ](max)
a bit ugly, i'm not sure where to put these. a mixin?

2021-02-26 09:19 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +AGG_MAX = Symbol("MAX")
where should these be defined?

2021-02-26 09:19 UTC, tgy commented on neurolang/probabilistic/query_resolution.py
> +        )
not sure about the best error message. this is a proposal

2021-02-26 09:28 UTC, demianw commented on neurolang/frontend/probabilistic_frontend.py
> +        ](max)
yes, the `TypedSymbolTableMixin` has a way to add functions in mixins (see `included_functions`) which but this was not implemented for symbols

2021-02-26 09:31 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +        )
It's OK. Do you want to add the `n_repeated_tuples` and `length` or the name of the rule as parameters to the Error such that we can catch and rethrow later with another message, if needed, at the fronted level? I think we should prepare things to not throw any IR exception from the frontend and make it easy for the front-end to catch and re-throw the errors which can be specific to each different frontend

2021-02-26 09:32 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +AGG_MAX = Symbol("MAX")
If we are adding default aggregations maybe in the datalog aggregation module?

2021-02-26 14:20 UTC, demianw commented on neurolang/datalog/aggregation.py
> +        return numpy.max(iterable)
It's not a good idea to wrap them this way, as for instance Pandas will detect or use the `np.max` or `np.mean` functions and used optimised versions. You optimised for cases like this in the RA solver module.

2021-02-26 15:01 UTC, tgy commented on neurolang/datalog/aggregation.py
> +        return numpy.max(iterable)
do you mean to use Python's builtin `max` function? what about the `mean` aggregation? there is no builtin for this one

2021-02-26 15:02 UTC, demianw commented on neurolang/datalog/aggregation.py
> +        return numpy.max(iterable)
I mean providing a symbol which points to a constant with `np.max` or `np.mean` instead of a wrapping function.

2021-02-26 15:02 UTC, demianw commented on neurolang/datalog/aggregation.py
> +        return numpy.max(iterable)
same way you did with `np.exp`

2021-03-02 08:35 UTC, demianw commented on neurolang/probabilistic/query_resolution.py
> +        )
@tgy on a second note these checks should be `optional`, as they could have a great computational cost. We should discuss with @jonasrenault on maybe making a singleton class which holds all configuration settings for NeuroLang (as he does for the RA backend) such that these options could be centralised.

2021-03-10 14:47 UTC, demianw requested changes
Good advancement, some things to change still

2021-03-10 14:47 UTC, demianw commented on neurolang/expressions.py
> +    def add_included_constant_functions_to_symbol_table(self) -> None:
this is better as a `constant_keyword_symbols` no? Nothing in what you did is specific to functions but just to symbols pointing to constants. Can you rename it everywhere else?
Also the use of a dictionary with a specific name means that the mixin strategy will fail if there are more than two mixins defining symbols. Why didn't you just copy the strategy with `included_functions` by adding constants, something like
```python
class MyNewMixin:
    constant_exp = Constant(np.exp)
```
 or something like that? Then you just have to copy __exactly__ the way it's done with functions but with constants.

2021-03-10 14:47 UTC, demianw commented on neurolang/relational_algebra.py
> +    def numpy_mean(self, fa):
maybe we could just make a dictionary with all these and implement it as cleanly as with the `OPERATOR_STRING` case for the arithmetic operators?

2021-03-10 14:52 UTC, tgy commented on neurolang/expressions.py
> +    def add_included_constant_functions_to_symbol_table(self) -> None:
sounds good, did not understand that this was what you had in mind. now i get it

2021-03-10 14:53 UTC, tgy commented on neurolang/relational_algebra.py
> +    def numpy_mean(self, fa):
yes, i thought of doing it but as i was pressured by time i went for the path of least resistance. i'll do that

2021-03-12 13:03 UTC, demianw requested changes
Almost there!

2021-03-12 13:03 UTC, demianw commented on neurolang/relational_algebra.py
> +TRANSLATABLE_NUMPY_OPERATION = {
this will work with any operation no? It doesn't have to be numpy. In fact python's built-ins `max`, `min`, `round`, `pow` and `math` module `log`, `sqrt`, `exp`, etc could be easily added too now. All being translated to the corresponding ANSI SQL or  PANDAS/Numexpr functions which are listed here https://numexpr.readthedocs.io/projects/NumExpr3/en/latest/user_guide.html#supported-functions https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html#computations-descriptive-stats

you can take 10 minutes to make the full list and then you are done instead of making a PR per new operation that you need.

this of course deprecates #612

2021-03-30 15:59 UTC, demianw approved these changes
Two small changes and it's in.

2021-03-30 15:59 UTC, demianw commented on neurolang/datalog/expression_processing.py
> +                raise ForbiddenExpressionError(
Can you make a more specific exception class? This will help having better error reporting in the frontend.

2021-03-30 15:59 UTC, demianw commented on neurolang/relational_algebra.py
> +        getattr(
this is very complex i.e. low maintenability code. Can you make proper loops and ifs and a function and then just calls
`EVAL_OP_TO_STR = f()` ?

2021-03-30 19:49 UTC, demianw commented on neurolang/relational_algebra.py
> +        {
and you still kept the super complex and unmaintainable code with the dictionary defined with inline ifs.

2021-03-30 19:49 UTC, demianw commented on neurolang/relational_algebra.py
> +        {
That's what I meant by `Can you make proper loops and ifs`

2021-04-23 14:57 UTC, demianw approved these changes
Two small details and then merge

2021-04-23 14:57 UTC, demianw commented on neurolang/relational_algebra.py
> +    def translatable_numpy_operation(self, fa):
This is not numpy specific anymore, maybe `translatable_operation`

2021-04-23 14:57 UTC, demianw commented on neurolang/datalog/expression_processing.py
> +            if isinstance(old_arg, FunctionApplication) and any(
If you want to check for aggregation, there is a specific class to distinguish aggregations from functions in the head: `AggregationApplication`

2021-04-23 15:11 UTC, tgy commented on neurolang/datalog/expression_processing.py
> +            if isinstance(old_arg, FunctionApplication) and any(
I've updated the code to check for an `AggregationApplication` instead. I think this is what you meant but I have a small doubt. Confirmed?

2021-04-23 15:11 UTC, tgy commented on neurolang/relational_algebra.py
> +    def translatable_numpy_operation(self, fa):
Done!

2021-04-23 15:12 UTC, tgy commented on neurolang/datalog/expression_processing.py
> +        is not a constant or an extensional/intensional predicate.
Just a small typo that was wrongly fixed by a recent commit from some open source contributor

2021-04-24 15:45 UTC, merged