Parser/Xrewriter Optimization
NeuroLang/NeuroLang pull request #623
Opened 2021-05-27 08:49 UTC by gzanitti

I made some modifications to the Parser and the Xrewrite algorithm to optimize queries that include ontological information.

Among the design decisions involved:
- The parser now returns a dictionary of constraints organized according to the functor of the consequent of the rules. Xrewriter now takes this input, allowing to minimize the number of iterations.
- Now the parser also returns a set of rules, organized in the same way as the constraints, and a new operation `_add_bulk_rules` allows to enter them in the program base without using the walk operation.

2021-05-31 11:05 UTC, demianw requested changes
Some reviews to understand code better.

2021-05-31 11:05 UTC, demianw commented on neurolang/frontend/probabilistic_frontend.py
> +            self.current_program_rewrited = det_idb
This might be dangerous what happens if there are different queries executed? Is the rewriting triggered at each point? Is this variable supposedly observable?

2021-05-31 11:05 UTC, demianw commented on neurolang/datalog/basic_representation.py
> +        self.symbol_table[symbol] = Union(rules)
Does this add one set of rules for a single symbol? Can you add the documentation?

2021-05-31 11:05 UTC, demianw commented on neurolang/datalog/constraints_representation.py
> +    def set_constraints(self, categorized_constraints):
can you add documentation? What does it mean for a constraint to be "categorised"?

2021-05-31 11:31 UTC, gzanitti commented on neurolang/frontend/probabilistic_frontend.py
> +            self.current_program_rewrited = det_idb
The main idea is to be able to have a variable to observe the rewrite from the frontend. It's executed each time a query is solved (if it involves a rewrite).  Do you think it's not necessary?

2021-05-31 11:31 UTC, gzanitti commented on neurolang/datalog/basic_representation.py
> +        self.symbol_table[symbol] = Union(rules)
Yes, exactly. I will add the documentation, thank you!

2021-06-02 09:26 UTC, demianw commented on neurolang/frontend/probabilistic_frontend.py
> +            self.current_program_rewrited = det_idb
Oh! If that's the point it's OK.

2021-06-02 13:13 UTC, gzanitti commented
> Some reviews to understand code better.

@demianw I documented most of the functions to make it easier to keep track of the code.

2021-06-10 06:12 UTC, demianw commented on neurolang/frontend/probabilistic_frontend.py
> +            self.current_program_rewrited = det_idb
`rewrited` does not exist in English, it's an irregular verb

2021-06-10 06:13 UTC, demianw commented
> > Some reviews to understand code better.
> 
> @demianw I documented most of the functions to make it easier to keep track of the code.

Some of the comments where I asked for documentation are not addressed yes

2021-06-10 11:43 UTC, gzanitti commented
@demianw Ready to be reviewed. Looking forward to your comments :)

2021-07-15 11:48 UTC, gzanitti commented
- [x] Clean code.
- [x] Documented functions.
- [x] All tests working.
- [x] Description of changes.

It seems to be ready for review

2022-01-13 15:06 UTC, demianw reviewed
First review!

2022-01-26 11:26 UTC, demianw requested changes
Final changes

2022-01-26 11:26 UTC, demianw commented on neurolang/datalog/constraints_representation.py
> +        This indexation is useful to obtain the constraints in the
"indexing"

2022-01-26 11:26 UTC, demianw commented on setup.cfg
> +  sqlalchemy
sure that we can remove the minimal version for sqlalchemy?

2022-01-26 11:26 UTC, demianw commented on setup.cfg
> +  rdflib
won't we need an "rdflib>6.0.0" now?

2022-02-23 15:37 UTC, gzanitti commented on setup.cfg
> +  sqlalchemy
That's the way we have it in master. The versioning was added by me trying to solve the problem I had, but it turned out to be related to something else (it was a test).

Also, I limited the version of tatsu, from version 5.0 onwards they don't support python 3.7. I raised the minimum version of pandas, 1.2.0 gives problems in some operations but CircleCI didn't notice it because it always ran on versions higher than 1.3.5.
Finally, I had to restrict the maximum version of pytest to avoid a bug in the tornado tests for the web app.

2022-02-23 15:38 UTC, gzanitti commented
I think it's ready to be merged finally. The last changes were only on the setup.cfg to guarantee that we can run against a clean version of python 3.7 without problems (I explained the modifications in a comment, above this one).

2022-02-24 18:42 UTC, merged