LQP Disjoint Project for Probabilistic Choices
NeuroLang/NeuroLang pull request #649
Opened 2021-07-09 07:45 UTC by tgy

- First implementation of the full dichotomy theorem. To be tested and refactored later
- Adding the lift_r algorithm
- Lifting code simplified by working on UCQ semantics
- Code cleanup
- Code cleanup
- More code cleanup
- More code cleanup
- Squashed commit of the following:
- WIP
- WIP
- add intractable queries
- test_example_4_6_a_really_simple_query
- Various improvements
- wip
- Code quality
- test_example_4_7_a_query_with_self_joins
- Better tests and result quality
- Corrections
- Add existential quantifiers to intractable queries, thereby fixing the test
- Added RAP weighted join
- Several changes
- Refactoring, increasing testing, documenting
- Added missing file
- Missing modifications
- Refactoring
- Added dalvi-suciu based solver and passing most tests
- Removed unused imports
- Added support to dalvi-suciu for handling constant variables
- All tests for lifted computation passing
- Refactored separator strategy
- Small code notation change
- Remove old tests
- Code quality
- Code quality
- Refactoring and documenting
- fix test + commutative comparator between n-ary ra exp
- fix test by moving to Constant[ColumnStr]
- add tractable query with intractable subquery test (4.8)
- fix the tests
- Refactoring and documentation
- correcting dumb bug
- enable tests on frontend + marg tests
- tests passing
- Fixed MoveQuantifiersUp
- fix doc
- wip
- first passing test
- passing tests
- re-enabling solvers
- add temporary dict.get fix
- Squashed commit of the following:
- fix
- fix imports
- fix
- add temporary fix
- skip intractable subquery test for now
- fix style
- fix based on demianw comment
- style
- add failing test
- fix test
- re-add documentation
- adress demianw's comments
- re-enable all tests
- Skip test_example_4_8_tractable_query_intractable_subquery
- Squashed commit of the following:
- remove old test file
- fix some of the tests
- further fixing issues
- all tests passing, skipping the WMC problematic ones
- use xfail instead of skip
- fix empty set test
- update
- improve coverage
- Squashed commit of the following:
- First implementation of the full dichotomy theorem. To be tested and refactored later
- Adding the lift_r algorithm
- Lifting code simplified by working on UCQ semantics
- Code cleanup
- Code cleanup
- More code cleanup
- More code cleanup
- WIP
- WIP
- add intractable queries
- test_example_4_6_a_really_simple_query
- wip
- Various improvements
- test_example_4_7_a_query_with_self_joins
- Code quality
- Better tests and result quality
- Corrections
- Add existential quantifiers to intractable queries, thereby fixing the test
- Added RAP weighted join
- Several changes
- Refactoring, increasing testing, documenting
- Added missing file
- Missing modifications
- Refactoring
- Added dalvi-suciu based solver and passing most tests
- Removed unused imports
- Added support to dalvi-suciu for handling constant variables
- All tests for lifted computation passing
- Refactored separator strategy
- Small code notation change
- Remove old tests
- Code quality
- Code quality
- Refactoring and documenting
- fix test + commutative comparator between n-ary ra exp
- fix test by moving to Constant[ColumnStr]
- add tractable query with intractable subquery test (4.8)
- fix the tests
- Refactoring and documentation
- correcting dumb bug
- enable tests on frontend + marg tests
- tests passing
- Fixed MoveQuantifiersUp
- Squashed commit of the following:
- add temporary fix
- skip intractable subquery test for now
- fix style
- fix based on demianw comment
- style
- add failing test
- fix test
- re-add documentation
- adress demianw's comments
- re-enable all tests
- remove old test file
- fix some of the tests
- Squashed commit of the following:
- further fixing issues
- all tests passing, skipping the WMC problematic ones
- use xfail instead of skip
- fix empty set test
- update
- improve coverage
- Squashed commit of the following:
- update
- update
- remove unwanted changes
- remove unwanted changes
- fix
- remove unwanted changes
- update
- update
- remove unwanted changes
- unwanted
- unwanted
- all tests passing
- fixes
- all tests passing

2021-07-09 07:49 UTC, tgy commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> +    assert_almost_equal(res.to_unnamed(), expected)
Small issue to to comparison of resultings probabilities (numerical precision)

2021-07-09 07:49 UTC, tgy commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> -    assert_almost_equal(result, expected)
Removing this as the probabilistic table is ill-formed (multiple probability labels for the same tuple) so there is no point checking the result

2021-07-09 07:49 UTC, tgy commented on neurolang/probabilistic/cplogic/testing.py
> -
Removing dead code (there is more to remove but we can do this in another PR)

2021-07-09 09:35 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> -        ra_query = _project_on_query_head(ra_query, shattered_query)
This is actually an unneeded step

2021-07-09 09:47 UTC, demianw commented on neurolang/frontend/tests/test_probabilistic_frontend.py
> -    assert_almost_equal(result, expected)
Can't you just leave the tests but put them in scopes instead of environments?

2021-07-09 09:49 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return self.projection_rap(
A more correct strategy would be to rewrite the DisjointProjection expression as a Projection expression, and walk again, instead of calling something in a mixin that you are assuming that it would be coded in other classes

2021-07-13 09:00 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +class LiftedQueryProcessingSemiringSolver(
All of this addition is more appropriately included in the same place as I included the `WeightedNaturalJoin`

2021-07-13 09:01 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        flat_query_body = lift_optimization_for_choice_predicates(
If the LQP works in the BID case we handle this optimisation shouldn't be needed anymore. Am I right?

2021-07-13 09:02 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        assert isinstance(symbol_table[atom.functor], ProbabilisticChoiceSet)
Asserts should never be in non-testing code. These should be exceptions.

2021-07-13 09:03 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +class LiftedQueryProcessingSemiringSolver(
I'll move it there

2021-07-13 09:06 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    return isinstance(symbol_table.get(atom.functor), ProbabilisticChoiceSet)
This indirection is so small and trivial that it makes code more difficult to read. Please try and avoid the overuse of auxiliary functions

2021-07-13 09:07 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        and all(isinstance(arg, Constant) for arg in atom.args)
You'll also need to ensure that the functor is a symbol, isn't that the case? That bug is hidden in your indirection.

2021-07-13 09:10 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    Makes the assumption that the atom is probabilistic.
This assumption is not needed. If the atom is deterministic or probabilistic fact set the set should be empty.

2021-07-15 12:08 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    return isinstance(symbol_table.get(atom.functor), ProbabilisticChoiceSet)
I got inspired by your own function
```python
def is_atom_a_deterministic_relation(atom, symbol_table):
    return isinstance(
        symbol_table.get(atom.functor, None),
        DeterministicFactSet
    )
```
When I remove this, I find the code less trivial to understand. But if you insist, I can remove it and copy paste the content of this function wherever it is called

2021-07-15 12:30 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    return isinstance(symbol_table.get(atom.functor), ProbabilisticChoiceSet)
You are right, keep it.

2021-07-15 12:35 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        flat_query_body = lift_optimization_for_choice_predicates(
Let the query be `ans(x, y) :- Q(x, y), P(x), P(y)`, where `Q` is a probabilistic fact relation and where `P` is a probabilistic choice relation. The `lift_optimization_for_choice_predicates` function produces a rewriting of the query as `ans(x, y) :- Q(x, y), P(x), P(y), x = y`, which is then unified as `ans(x, y) :- Q(y, y), P(y)`. This is however not done by the BID extension of the Dalvi/Suciu algorithm, if I am not wrong.

2021-07-15 13:21 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        flat_query_body = lift_optimization_for_choice_predicates(
I'm sure that your optimisation, when applicable, makes for better queries. The issue is, under which cases the optimisation yields a query that produces the right probabilities. Your optimisation works well with CQs, the issue is when to apply it.

2021-07-15 13:24 UTC, demianw commented on neurolang/relational_algebra.py
> +            return self.walk(
Why was this change introduced? Was it necessary? Or you just disagreed with my style? Same as above. And if it was not necessary, isn't this just complexifying the PR in an unnecessary case?

2021-07-15 13:24 UTC, demianw commented on neurolang/relational_algebra.py
> +            type(e) is type(e.relation)
isn't this assured by the patter match?

2021-07-19 18:43 UTC, demianw requested changes
Good job! First round of comments

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    _maybe_reintroduce_head_variables,
If we need to import it, then it shouldn't start with `_` as it's not an internal function too. Probably change the name to "add_head_constants_to_projected_variables" or something like this

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        solver = LiftedQueryProcessingSemiringSolver(symbol_table)
I think it's not a semiring anymore as it has to `+`-style operations

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return rap.IndependentProjection(result, proj_cols)
Is it this projection the appropriate one regardless of wether the rule is made of a query with all-deterministic predicates, a fact set, or a choice set?

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
being it a tuple, isn't it easier to do 
```python
tuple(f for f in dnf_query.formulas[1:])
```
?


If you agree, then per convention change `first` and `second` by `head` and `tail`.

Also, are we sure that any split in head and tail will maintain liftability? Or we need to pick this in a smart way?

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction((first,) + second.formulas),
isn't this just `dnf_query.formulas`?

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +def disjoint_project(rule_dnf, symbol_table):
Documentation :) ?

2021-07-19 18:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return disjoint_project_cnf(rule_dnf.formulas[0], symbol_table)
I think here it is "project_disjunction" and "conjunction" and not disjunctive normal form (dnf) and conjunctive normal form (cnf). You don't really care about the structure of the query inside of the operation, only if it is liftable.

2021-07-20 22:03 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
Based on Suciu et al. it can be **any other UCQ query**, and so they do not mention a "smart way" of splitting, just finding a CQ that has a probabilistic choice

> Second, suppose Q is a UCQ query of the form Q = Q1 ∨ Q' where Q1 is a conjunctive
query having an atom where all key attribute are constants, and Q' is any other UCQ query.
Then we write P (Q) = P (Q1) + P (Q') − P (Q1 ∧ Q' ), then apply the disjoint-project rule
both to Q1 and to Q1 ∧ Q'.

2021-07-20 22:05 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return rap.IndependentProjection(result, proj_cols)
In the deterministic case, you are right: the `Projection` is sufficient, although the `IndependentProjection` also works (but going for the `Projection` is faster). In the case of a probabilistic fact table, the `IndependentProjection` is the right projection due to the tuple-independence assumption. In the case of a probabilistic choice, the algorithm should always use a `DisjointProjection` if there are existentially-quantified variables occurring in the probabilistic choice.

2021-07-21 06:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return rap.IndependentProjection(result, proj_cols)
So then, the point of my question, shouldn't this be implemented differently?

2021-07-21 06:46 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
So then we should implement the strategy we discussed orally on July 20th

2021-07-21 07:02 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return rap.IndependentProjection(result, proj_cols)
If you look at the last version of the code, I changed this back to a `Projection`

2021-07-21 07:06 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
I don't see the point here. You're given a UCQ in the form `Q1 v Q2 v ... v Qn`, where `Q1, ..., Qn` are CQs. It suffices to look for one CQ `Qi` that has a probabilistic choice, and defines `Q'` as the disjunction of all remaining `Qj, j != i`. Maybe I don't understand something, but I don't see what this strategy is going to add.

2021-07-21 07:30 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
Well, what happens if there is more than one which is liftable as a prob-choice, leaving two options `Qi v Q'` and `Qi' v Q''`. Then suppose that `Q'` is not liftable but `Q''` is. Then, unless we can produce an argument ensuring that this case (where there are two decompositions where one is liftable and the other isn't) doesn't exist, we should put in the proper strategy. Do you think this assurance is possible? It might

2021-07-21 07:38 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
That makes sense. I will try to find an example of such query because we need to test this!

2021-07-21 07:40 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        Conjunction(tuple(f for f in dnf_query.formulas if f != first)),
Maybe you can prove that this can't happen, but you need to be sure

2021-07-26 11:09 UTC, demianw commented
The test not passing and PR #660 seems to come from our decompositions not respecting section 2.6 in Dalvi Suciu JACM 2012. We need to find a series of transforms that enables us to do that.

2021-08-04 10:05 UTC, demianw commented
@tgy why did you close this branch and deleted it?

2021-08-04 10:07 UTC, tgy commented
Accident! I was cleaning up some other branches and accidentally deleted this one. This is fixed now

2021-08-18 12:10 UTC, demianw requested changes
Some issues with your approach.

2021-08-18 12:10 UTC, demianw commented on neurolang/probabilistic/small_dichotomy_theorem_based_solver.py
> +def _get_existential_variables_in_atoms(query, functor_type):
isn't this just `get_logic_free_variables(shattered_query.antecedent)-set(shattered_query.consequent.args)`?

2021-08-18 12:10 UTC, demianw commented on neurolang/probabilistic/small_dichotomy_theorem_based_solver.py
> +            raise UnsupportedSolverError(
But we could solve choice existentials, couldn't we? If not none of the queries in your submitted paper are valid. Can you please explain this to me?

2021-08-18 12:21 UTC, tgy commented on neurolang/probabilistic/small_dichotomy_theorem_based_solver.py
> +def _get_existential_variables_in_atoms(query, functor_type):
No because it only gets those existentially-quantified variables occurring in atoms matching the `functor_type` argument, which is going to be either `ProbabilisticFactSet` or `ProbabilisticChoiceSet`.

Your proposal gets **all** existientally-quantified variables, independently of the functor type

2021-08-18 12:23 UTC, tgy commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    else:
The else is not part of the last version of the code. I think you commented an outdated version. I don't see the else on the last version on GitHub or on my local repository

2021-08-18 12:25 UTC, tgy commented on neurolang/probabilistic/small_dichotomy_theorem_based_solver.py
> +            raise UnsupportedSolverError(
Yes! Sorry, this error message is wrong and I forgot to update it. To be clear, the case for which we raise this exception is whenever there is an existientally quantified variable that occurs in a probabilistic fact atom, without occurring in a probabilistic choice atom. If it occurs in a probabilistic choice atom then we have mutual exclusivity, but if if does not then we need to do an independent projection with a noisy-or aggregation, and we defer to the full dichotomy solver.

2021-08-18 14:22 UTC, tgy commented on neurolang/probabilistic/tests/test_dalvi_suciu_lift.py
> +    ProbabilisticChoiceSet,
Will add tests for that!

2021-08-19 07:28 UTC, demianw requested changes
Last changes, hopefully

2021-08-19 07:28 UTC, demianw commented on neurolang/probabilistic/small_dichotomy_theorem_based_solver.py
> +    if isinstance(query.antecedent, Conjunction):
Simplify the code below with `extract_logic_atoms`

2021-08-19 07:28 UTC, demianw commented on neurolang/probabilistic/tests/test_dalvi_suciu_lift.py
> +    ProbabilisticChoiceSet,
Good! Check that the proper solver is used in the tests.

2021-08-24 09:48 UTC, demianw reviewed
Last comment

2021-08-24 09:48 UTC, demianw commented on neurolang/relational_algebra_provenance.py
> +    @add_match(Union(ProvenanceAlgebraSet, ProvenanceAlgebraSet))
Is there a guarantee that this is how we should always implement the union? Is this specified in Suciu?

2021-08-24 09:55 UTC, merged