Enable UCQ Shattering
NeuroLang/NeuroLang pull request #654
Opened 2021-07-15 09:37 UTC by tgy

- add UCQ shattering test
- update

2021-07-15 10:01 UTC, demianw requested changes

2021-07-15 10:01 UTC, demianw commented on neurolang/probabilistic/shattering.py
> +    query = RemoveConjunctionDuplicates().walk(query)
maybe the best would be to convert it to DNF (there is a function for that) before shattering. Then you know it's a disjunction of conjunctions. And moreover, you should make it ignore conjunctive queries with negation. In that way, it runs for all queries, but for some, it does nothing.

2021-07-19 15:23 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +                cache_key += (i,)
The cache key contains the constants and the indices of the non-constant terms (symbols) such that the same key is given to `P(a, x)` and `P(a, y)` but not the same for `P(a, x)` and `P(b, x)`

2021-07-19 15:24 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +        antecedent = Conjunction(tuple(set(antecedent.formulas)))
I have to remove the duplicated conjuncts to handle corner cases. I'm not sure this is the right place to do so. Maybe we should have our algorithms ensure that formulas are not duplicated?

2021-07-19 15:27 UTC, demianw commented on neurolang/probabilistic/shattering.py
> +            return query
Seems that you can't shatter a disjunct with a negation. I think this is not true. If you have: 
Q1 v Q2 v Q3 you can shatter them separately, and if one has a negation, then you just avoid shattering that one.

2021-07-20 13:45 UTC, tgy commented on neurolang/datalog/expression_processing.py
> +    return implication.apply(implication.consequent, antecedent)
This function should not take care of removing duplicates in the conjunction. This is fixed.

2021-07-20 13:46 UTC, tgy commented on neurolang/logic/transformations.py
> +        return self.walk(self._nary_op_without_duplicates(conjunction))
Only walking disjunctions and conjunctions because there is a semantic equivalence when duplicates of disjuncts or conjuncts are removed, which is not necessarily the case for all n-ary logic operators

2021-07-20 13:46 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +    return query.apply(query.consequent, new_antecedent)
Just moved this up to separate functions and walkers

2021-07-20 13:47 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +        return self.walk(conjunctive_query)
Rewrite and delegate to the next pattern

2021-07-20 13:47 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +        tagger = QueryEasyShatteringTagger()
Tag predicates in each conjunction separately

2021-07-20 13:48 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +    shattered = RemoveTrivialOperations().walk(shattered)
Re-simplify the query if we added trivial conjunctions / disjunctions

2021-07-20 13:53 UTC, demianw requested changes
Looks great! Very last extremely trivial comments

2021-07-20 13:53 UTC, demianw commented on neurolang/probabilistic/shattering.py
> +    def _shatter_conjunction(self, conjunction):
I think you might just be able to compose `EasyQueryShatterer` and `QueryEasyShatteringTagger` as I don't think there are overlapping patterns. Am I right?

2021-07-20 13:53 UTC, demianw commented on neurolang/logic/transformations.py
> +class RemoveDuplicatedConjunctsDisjuncts(ExpressionWalker):
If you make this inherit from `LogicExpressionWalker` it will automatically walk recursively through all subexpressions that don't match those here.

2021-07-20 13:53 UTC, demianw commented on neurolang/probabilistic/shattering.py
> +    shattered = RemoveTrivialOperations().walk(shattered)
Nice clean code!

2021-07-20 14:23 UTC, demianw commented on neurolang/datalog/expression_processing.py
> +    antecedent = enforce_conjunction(implication.antecedent)
One more, will `enforce_conjunction` be the same as the existing `GuaranteeConjunction`?

2021-07-20 14:27 UTC, demianw commented on neurolang/probabilistic/shattering.py
> +        tagger = QueryEasyShatteringTagger()
But do we need that? I thought that if we are just shattering constant selections of the shape `P(a, x)` we need to keep track of them across all conjuncts to track dependancies

2021-07-20 14:56 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +    def _shatter_conjunction(self, conjunction):
Done

2021-07-20 14:56 UTC, tgy commented on neurolang/logic/transformations.py
> +class RemoveDuplicatedConjunctsDisjuncts(ExpressionWalker):
Done

2021-07-20 14:56 UTC, tgy commented on neurolang/datalog/expression_processing.py
> +    antecedent = enforce_conjunction(implication.antecedent)
Done, refactored

2021-07-20 14:58 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +        tagger = QueryEasyShatteringTagger()
True, this should be checked accross conjuncts within the disjunction. And it should fail if there is a dependency between two disjuncts as well. See the test with query `ans(x, y) :- ( P(a, x) ^ Q(x, y) ) v ( Q(y, hello) ^ P(a, x) ^ P(b, y) )` as an example where `Q(x, y)` and `Q(y, hello)` do generate a dependency and therefore the **Union** LQP rule cannot be applied because the query cannot be written as `Q = Q1 v Q2` where `Q1` and `Q2` are independent

2021-07-20 14:59 UTC, demianw approved these changes
Looks great! Will merge once all tests pass

2021-07-20 14:59 UTC, tgy commented on neurolang/probabilistic/shattering.py
> +        tagger = QueryEasyShatteringTagger()
This is now fixed

2021-07-20 16:07 UTC, merged