Existential Issue when rewriting UCQs in LQP algorithm
NeuroLang/NeuroLang pull request #660
Opened 2021-07-22 10:05 UTC by tgy

2021-07-26 15:54 UTC, demianw commented
@tgy as this is the same bug which is failing in PR #649 we will solve it here. @gzanitti agreed to take over/

2021-09-06 13:43 UTC, gzanitti commented
@demianw I couldn't call for review from the github feature, so I'm adding a comment:
I think this PR is ready for review.

2021-09-06 14:10 UTC, demianw requested changes
Some comments to address

2021-09-06 14:10 UTC, demianw commented on neurolang/probabilistic/transforms.py
> +def convert_to_union_cnf(query):
I don't think we are using this anymore. Can we put it in a different PR?

2021-09-06 15:28 UTC, gzanitti commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    final_expression = minimize(final_expression)
> If you minimize after, as minimize_cnf/dnf have the "remove trivial operators" included, will this break the structure of separating in term-connected conjunctions?
> We might want to look for a general minimiser that minimises expressions based on proposition 2.13 of Dalvi & Suciu (2012) in another PR (issue)

Your point makes sense. The match `@add_match(NaryLogicOperator, lambda e: len(e.formulas) == 1)`, raises some doubts in me since it could disappear external conjunctions/disjunctions.
For the moment, I will remove the operation inside the minimization walker. As you say, we should deal with it in the future (maybe I should create an issue so we don't forget it?).

2021-09-06 15:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    final_expression = minimize(final_expression)
Oh! Actually, this won't be a problem. I thought that that operator was collapsing disjunctions and conjunctions, if that's not happening, then we're OK

2021-09-10 09:00 UTC, demianw commented
@gzanitti is this PR ready? Can you handle the conflicts such that I can merge?

2021-09-10 09:20 UTC, gzanitti commented
> @gzanitti is this PR ready? Can you handle the conflicts such that I can merge?

Of course, I will do it right now.

2021-09-10 10:55 UTC, gzanitti commented
@demianw Sorry for the delay, the connection was quite unstable and I could not push. Now it's ready.

2021-09-10 11:19 UTC, gzanitti commented
The conflict is solved, but there is a test that fails at the moment when the expression enters the query solver walker at https://github.com/NeuroLang/NeuroLang/blob/7196d99c15342a573c7b9d66e2948f279d9c64ab/neurolang/probabilistic/dalvi_suciu_lift.py#L180

I'm going to check what's going on.

2021-09-10 15:57 UTC, gzanitti commented
@demianw the issue has been solved :)

2021-09-10 16:06 UTC, merged