Antishattering
NeuroLang/NeuroLang pull request #727
Opened 2022-04-22 13:53 UTC by gzanitti

2022-04-26 12:04 UTC, demianw reviewed
Small comments

2022-04-26 12:04 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        if len(proyected_variables) > 0 and new_selection:
Here you should project even if there are not anymore variables if not the case of boolean queries might not work.

2022-04-26 12:04 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +class ProjectionSelectionByPChoiceConstant(PatternWalker):
Maybe we should make an anti-shattering module? And include this in the chained walker at the end of the dalvi-suciu implementation

2022-04-27 07:06 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +    _selfjoins_in_pchoices
Avoid using underscore function names for functions exported from the module

2022-04-27 07:07 UTC, demianw commented on neurolang/probabilistic/tests/test_antishattering.py
> +
Add at least a disjunction case to the tests

2022-04-27 07:08 UTC, demianw commented on neurolang/probabilistic/antishattering.py
> +    @add_match(RelationalAlgebraOperation)
Maybe this should match a ProvenanceAlgebraSet

2022-05-02 08:00 UTC, gzanitti commented on neurolang/probabilistic/tests/test_antishattering.py
> +
The use of disjunctions causes the query to be non-conjunctive and NeuroLang returns an error. Should I make a test that captures this situation?

2022-05-02 08:15 UTC, demianw commented on neurolang/probabilistic/tests/test_antishattering.py
> +
Neurolang shouldn't return an error when the query is non conjunctive. In fact, a segregation query is non conjunctive too.

Can you add the test so we can work on it?

2022-05-02 08:28 UTC, gzanitti commented on neurolang/probabilistic/tests/test_antishattering.py
> +
Done. This is where the issue comes from:
https://github.com/NeuroLang/NeuroLang/blob/41a5de6ab421f2f53ed0039cdc257dfc6bb3336e/neurolang/datalog/negation.py#L97

2022-05-02 08:30 UTC, demianw commented on neurolang/probabilistic/tests/test_antishattering.py
> +    cpl_program.walk(query)
The problem with this test is that the `cpl_program` accepts only Datalog-compatible syntax. So you need to have the program

```
A():-P(a)
A():-P(b)
Ans():-A()
```

2022-05-03 07:31 UTC, demianw requested changes
Last comments!

2022-05-03 13:10 UTC, gzanitti commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +
The problem with this modification is that I need an instance of the flat_query here:
https://github.com/NeuroLang/NeuroLang/blob/59ea899e5da163240f989c29006ad8993fe6df42/neurolang/probabilistic/dalvi_suciu_lift.py#L210


If I do this modification inside `_prepare_and_optimise_query`, I lose the new variables introduced by `pchoice_constants_as_head_variables `.

If not, it should also return an instance of the query modified by `pchoice_constants_as_head_variables` at the end (in addition to the dictionary of constants to variables created inside), but I think that makes the code more complex.

2022-05-03 13:10 UTC, gzanitti commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        return NonLiftable(rule)
We decided to add it inside the `inclusion_exclusion_conjunction` method. But I need an instance of the query in dnf form to make it easier to parse. Is it ok if I add it as a condition in the if? 

https://github.com/NeuroLang/NeuroLang/blob/e34136de40fe4a0b04e5d3f0bbfa3683155fd7a5/neurolang/probabilistic/dalvi_suciu_lift.py#L334

It is much simpler to implement and the result should be the same.

2022-06-09 12:41 UTC, demianw commented on neurolang/probabilistic/antishattering.py
> +)
Maybe move to the same module as `WrappedNamedRelationalAlgebraFrozenSet`

2022-06-09 12:43 UTC, demianw commented on neurolang/probabilistic/dalvi_suciu_lift.py
> +        provenance_column = str2columnstr_constant(Symbol.fresh().name)
maybe outsource the RHS of the equality to a function? The code of DS is already very hard to follow.

2022-06-09 12:46 UTC, demianw commented on neurolang/probabilistic/tests/test_antishattering.py
> +from operator import eq
I think we need testing for cases with more than one parameter. Something like

`P(a, x) & P(y, b) & P(z, w)` and variations of these cases.

2022-06-15 13:28 UTC, gzanitti commented on neurolang/probabilistic/cplogic/testing.py
> +        and isinstance(pas2, ProvenanceAlgebraSet)
It was probably a change made by autoformatting. It is now disabled. Sorry.

2022-09-10 13:52 UTC, closed without merging